language: cpp

env: CXX_STANDARD=c++11

# Enable install caching to reduce install time in next builds
cache: ccache

compiler: g++

sudo: required

dist: trusty

before_install:
  - cd ../
  - sudo mv gr-lora ../
  - cd ../
  - sudo apt-get update

install:
  - sudo apt-get install g++-4.8
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  # Report correct versions are installed
  # - uname -a
  # - $CXX --version
  # - $CC --version

  - sudo pip install scipy
  - sudo apt-get install swig
  - sudo apt-get install libcppunit-dev
  - sudo apt-get install fftw3 fftw-dev libfftw3-dev

  - sudo apt-get install libboost1.55-all-dev
  - sudo apt-get install gnuradio
  - sudo apt-get install gnuradio-dev
  - sudo apt-get install liblog4cpp5
  - sudo apt-get install liblog4cpp5-dev
  - sudo ldconfig

  # Manual liquidDSP install
  - git clone https://github.com/jgaeddert/liquid-dsp.git
  - cd liquid-dsp/
  - sudo sh ./bootstrap.sh
  - sh ./configure
  - make && sudo make install
  - sudo ldconfig
  - cd ../

before_script:
  - cd gr-lora
  - mkdir build && cd build
  - cmake ../

script:
  - make
  - sudo make install

notifications:
  email: false
